# Assignment 1

### Jordan Yu 24604688

## Exercise 1:

In exercise 1, I will implement a function for Mean Absolute Error (MAE) based on the given predicted values and actual values. The function takes two lists, and each list CANNOT have NA values.

```{r}
maeFormula = function(predicted_list, actual_list){
  
  if(length(predicted_list) == length(actual_list) && 
     !anyNA(predicted_list, actual_list) &&
     length(predicted_list) != 0 && 
     length(actual_list) != 0 &&
     is.list(predicted_list) &&
     is.list(actual_list)
     ) {
    length_of_list = length(predicted_list)
    sum = 0
    for(i in 1:length_of_list){
      ae = abs(actual_list[[i]] - predicted_list[[i]])
      sum = ae + ae
    }
    mae = sum/length_of_list
    return(mae)
  } else {
    error = 'please ensure your inputs are correct'
    return(error)
  }
}
```

## Exercise 2 & Exercise 3

```{r, error = TRUE}

#' How to get the mean absolute error using a function but does not need any other library's help?
#' 
#' The function maeFormula is to calculate the mean absolute error or MAE based on the predicted results and their actual values you give. It returns MAE if all inputs have the same length, no NA/NULL values and the type of both lists is numeric, otherwise the function will not work and return an error message.
#' 
#' 
#' @param predicted_list the predicted results stored in a list without NA/NULL values. The reason why this parameter called predicted_list is that this is the list for predicted results.
#' @param actual_list the actual values stored in a list without NA/NULL values. The reason why this parameter called actual_list is that this is the list for actual values.
#'
#' @return mae  the computed mean absolute error result if all inputs are correct.
#' 
#' @export
#'
#' @examples

predicted_list_1 = list(1,2,3)
actual_list_1 = list(4,5,6)

maeFormula(predicted_list_1, actual_list_1) # returns mae = 2
maeFormula(list(23,54,89), c(22,43,65)) # returns error message as the second input argument is not list
maeFormula(list(23,54,89), list(22,43)) # returns error message as two input lists do not have the same length
```

## Exercise 4:

```{r}
library(testthat)

predicted_list_1 = list(1,2,3)
actual_list_1 = list(4,5,6)
actual_list_2 = list(7,8,9)

test_mae_function <- test_that("Testing maeFormula function", {
  expect_equal(maeFormula(predicted_list_1,actual_list_1),2)
  expect_error(maeFormula(predicted_list_1,actual_list_1,actual_list_2))
  expect_match(maeFormula(predicted_list_1,c(2,3)), "please ensure your inputs are correct")
})
```
